CREATE FUNCTION hashi8(i8) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/moreint', 'hashi8';
CREATE FUNCTION hashu8(u8) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/moreint', 'hashu8';
CREATE FUNCTION hashu16(u16) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/moreint', 'hashu16';
CREATE FUNCTION hashu32(u32) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/moreint', 'hashu32';
CREATE FUNCTION hashu64(u64) RETURNS int4 IMMUTABLE STRICT LANGUAGE C AS '$libdir/moreint', 'hashu64';
